version: '3.8'

services:
  backend:
    image: ghcr.io/amirtalbi/pouilleux-backend:latest
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ADMIN_PASSWORD=pouilleux-admin
    networks:
      - pouilleux-network
    # Ne pas exposer le port directement

  frontend:
    image: ghcr.io/amirtalbi/pouilleux-front:latest
    ports:
      - "80:80"       # HTTP (redirige vers HTTPS)
      - "443:443"
    depends_on:
      - backend
    networks:
      - pouilleux-network

networks:
  pouilleux-network:
    driver: bridge
